name: Deploy to S3 and Sync EC2

on:
  push:
    branches:
      - main  # 메인 브랜치에 코드가 올라올 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub에 올린 코드 가져오기
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. AWS 자격 증명 설정 (등록하신 Secret 사용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2  # 서울 리전

    # 3. S3로 파일 동기화 (배포)
    - name: Upload to S3
      run: |
        aws s3 sync . s3://본인의-버킷-이름 --delete --exclude ".git/*" --exclude ".github/*"
        # '본인의-버킷-이름' 부분을 실제 생성한 버킷 명으로 수정하세요!

    # 4. EC2에 접속하여 S3 파일 가져오기 (웹 서버 반영)
    - name: EC2 S3 Sync
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}        # EC2 퍼블릭 IP
        username: ec2-user                  # Amazon Linux 사용 시 기본값
        key: ${{ secrets.EC2_SSH_KEY }}     # .pem 키 파일의 텍스트 전체
        script: |
          sudo aws s3 sync s3://본인의-버킷-이름 /var/www/html --delete
          # 여기서도 '본인의-버킷-이름'을 수정하세요.